name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: |
          npm i -g pnpm
          pnpm install

      - name: Build Project
        run: |
          pnpm run build

      - name: Prepare SSH Environment
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Add Host to Known Hosts
        run: |
          ssh-keyscan ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Install rsync and sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync sshpass

      - name: Deploy to Server
        env:
          HOST: ${{ secrets.DEPLOY_HOST }}
          USER: ${{ secrets.DEPLOY_USER }}
          PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
          TARGET_DIR: /www/wwwroot/isyangs.cn
        run: |
          sshpass -p "${PASSWORD}" rsync -e "ssh -o StrictHostKeyChecking=no" -avz ./dist/ $USER@$HOST:$TARGET_DIR
