name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: pnpm

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies and build
        run: |
          pnpm install
          pnpm run build

      - name: Deploy to Server with Password
        env:
          HOST: ${{ secrets.DEPLOY_HOST }}
          USER: ${{ secrets.DEPLOY_USER }}
          PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
          TARGET_DIR: /www/wwwroot/isyangs.cn
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          sshpass -p "${PASSWORD}" rsync -avz ./dist/ $USER@$HOST:$TARGET_DIR
